# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ata_piix"
    "hpsa"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/52c6ecf6-ce63-43f9-b20a-15691c8380cc";
    fsType = "ext4";
  };

  fileSystems."/mnt/DATA1" = {
    device = "/dev/disk/by-uuid/f6d3a2cc-ba17-441e-8c84-149ce32d8076";
    fsType = "ext4";
  };

  fileSystems."/mnt/DATA2" = {
    device = "/dev/disk/by-uuid/c69628fa-11c7-4e4e-8f20-2e985def27e5";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp21s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp21s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp21s0f2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp21s0f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0f2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
