# This file is generated by 'just generate' or 'just clean'
# from the configuration file usr/config.yaml
# --> DO NOT EDIT <--

{ config, lib, ... }:
{
  disko.devices.disk.main.device = lib.mkForce "/dev/nvme0n1";
}
